# Generated by Django 5.1.6 on 2025-03-05 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuickserveBackend', '0003_alter_user_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
