# Generated by Django 5.1.6 on 2025-03-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
