# Generated by Django 5.1.6 on 2025-03-09 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_service_image_url'),
        ('core', '0003_rename_logo_url_category_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='Category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.category'),
            preserve_default=False,
        ),
    ]
