# Generated by Django 5.1.6 on 2025-03-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='pincode',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
